export default [
  'user.profile',
  'user.assets',
  'user.address',
  'payment.create',
  'navigate.back',
  'navigate.close',
  'ui.notice',
  'ui.confirm',
  'utils.setClipboard',
  'utils.screenshot',
  'utils.share',
  'utils.scanQR',
  'utils._choosePhoto',
  'utils._openUrl',
]
