export default [
  'user.profile',
  'user.assets',
  'user.address',
  'payment.create',
  'navigate.back',
  'navigate.close',
  'navigate.toggleNavBar',
  'ui.notice',
  'ui.confirm',
  'utils.choosePhoto',
  'utils.setClipboard',
  'utils.share',
  'utils.scanQr',
  'utils.openUrl',
]
